ARG PYTHON_VERSION 

# --------------------------------------------- base1
FROM python:${PYTHON_VERSION}-alpine as base1

# --------------------------------------------- final
FROM base1 as final

RUN apk add mc
RUN apk add bash

RUN adduser -D test

ADD --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres

USER test

ENTRYPOINT sh -c " \
set -eux; \
bash run_tests3.sh;"
