ARG PYTHON_VERSION=3.12

# --------------------------------------------- base1
FROM python:${PYTHON_VERSION}-alpine AS base1

ENV PYTHON_BINARY=python3

# --------------------------------------------- final
FROM base1 AS final

RUN apk add mc
RUN apk add bash

RUN adduser -D test

ADD --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres

USER test

ENTRYPOINT sh -c " \
set -eux; \
bash run_tests3.sh;"
